//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLiteExplorer.Resources.ScriptSQL {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SchemaInfos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SchemaInfos() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SQLiteExplorer.Resources.ScriptSQL.SchemaInfos", typeof(SchemaInfos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into History values (&apos;{0}&apos;);.
        /// </summary>
        internal static string AddDataBaseToHistory {
            get {
                return ResourceManager.GetString("AddDataBaseToHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete from history where history =&apos;{0}&apos;;.
        /// </summary>
        internal static string DeleteDataBaseFromaHistory {
            get {
                return ResourceManager.GetString("DeleteDataBaseFromaHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRAGMA table_info(&apos;{0}&apos;).
        /// </summary>
        internal static string GetColumnsByTable {
            get {
                return ResourceManager.GetString("GetColumnsByTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRAGMA foreign_key_list(&apos;{0}&apos;).
        /// </summary>
        internal static string GetForeignkeysByTable {
            get {
                return ResourceManager.GetString("GetForeignkeysByTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRAGMA index_list(&apos;{0}&apos;).
        /// </summary>
        internal static string GetIndexsByTable {
            get {
                return ResourceManager.GetString("GetIndexsByTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT tbl_name FROM sqlite_master WHERE type=&apos;table&apos; AND name NOT LIKE &apos;sqlite_sequence&apos;.
        /// </summary>
        internal static string GetTablesName {
            get {
                return ResourceManager.GetString("GetTablesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT name,tbl_name FROM sqlite_master WHERE type=&apos;trigger&apos; AND name NOT LIKE &apos;sqlite_sequence&apos;.
        /// </summary>
        internal static string GetTriggersName {
            get {
                return ResourceManager.GetString("GetTriggersName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT tbl_name FROM sqlite_master WHERE type=&apos;view&apos; AND name NOT LIKE &apos;sqlite_sequence&apos;.
        /// </summary>
        internal static string GetVewsName {
            get {
                return ResourceManager.GetString("GetVewsName", resourceCulture);
            }
        }
    }
}
